
package soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CorreoInvalidoFault", targetNamespace = "http://publicadores/")
public class CorreoInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CorreoInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CorreoInvalidoException_Exception(String message, CorreoInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CorreoInvalidoException_Exception(String message, CorreoInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.CorreoInvalidoException
     */
    public CorreoInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
