
package soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EdicionNoExisteFault", targetNamespace = "http://publicadores/")
public class EdicionNoExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EdicionNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EdicionNoExisteException_Exception(String message, EdicionNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EdicionNoExisteException_Exception(String message, EdicionNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.EdicionNoExisteException
     */
    public EdicionNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
