
package soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "FechaInvalidaFault", targetNamespace = "http://publicadores/")
public class FechaInvalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FechaInvalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FechaInvalidaException_Exception(String message, FechaInvalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public FechaInvalidaException_Exception(String message, FechaInvalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.FechaInvalidaException
     */
    public FechaInvalidaException getFaultInfo() {
        return faultInfo;
    }

}
