
package soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NombreTipoRegistroDuplicadoFault", targetNamespace = "http://publicadores/")
public class NombreTipoRegistroDuplicadoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NombreTipoRegistroDuplicadoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NombreTipoRegistroDuplicadoException_Exception(String message, NombreTipoRegistroDuplicadoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NombreTipoRegistroDuplicadoException_Exception(String message, NombreTipoRegistroDuplicadoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.NombreTipoRegistroDuplicadoException
     */
    public NombreTipoRegistroDuplicadoException getFaultInfo() {
        return faultInfo;
    }

}
