
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorRegistroService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:9130/publicadorRegistro?wsdl")
public class PublicadorRegistroService
    extends Service
{

    private static final URL PUBLICADORREGISTROSERVICE_WSDL_LOCATION;
    private static final WebServiceException PUBLICADORREGISTROSERVICE_EXCEPTION;
    private static final QName PUBLICADORREGISTROSERVICE_QNAME = new QName("http://publicadores/", "PublicadorRegistroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/publicadorRegistro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORREGISTROSERVICE_WSDL_LOCATION = url;
        PUBLICADORREGISTROSERVICE_EXCEPTION = e;
    }

    public PublicadorRegistroService() {
        super(__getWsdlLocation(), PUBLICADORREGISTROSERVICE_QNAME);
    }

    public PublicadorRegistroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORREGISTROSERVICE_QNAME, features);
    }

    public PublicadorRegistroService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORREGISTROSERVICE_QNAME);
    }

    public PublicadorRegistroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORREGISTROSERVICE_QNAME, features);
    }

    public PublicadorRegistroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorRegistroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorRegistro
     */
    @WebEndpoint(name = "PublicadorRegistroPort")
    public PublicadorRegistro getPublicadorRegistroPort() {
        return super.getPort(new QName("http://publicadores/", "PublicadorRegistroPort"), PublicadorRegistro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorRegistro
     */
    @WebEndpoint(name = "PublicadorRegistroPort")
    public PublicadorRegistro getPublicadorRegistroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PublicadorRegistroPort"), PublicadorRegistro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORREGISTROSERVICE_EXCEPTION!= null) {
            throw PUBLICADORREGISTROSERVICE_EXCEPTION;
        }
        return PUBLICADORREGISTROSERVICE_WSDL_LOCATION;
    }

}
