
package soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorRegistro", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorRegistro {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/estaRegistradoRequest", output = "http://publicadores/PublicadorRegistro/estaRegistradoResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/estaRegistrado/Fault/UsuarioNoExisteException")
    })
    public boolean estaRegistrado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns soap.DtRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/getRegistroRequest", output = "http://publicadores/PublicadorRegistro/getRegistroResponse")
    public DtRegistro getRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/altaTipoDeRegistroRequest", output = "http://publicadores/PublicadorRegistro/altaTipoDeRegistroResponse")
    public String altaTipoDeRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        double arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws EdicionNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/alcanzoCupoRequest", output = "http://publicadores/PublicadorRegistro/alcanzoCupoResponse", fault = {
        @FaultAction(className = EdicionNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/alcanzoCupo/Fault/EdicionNoExisteException")
    })
    public boolean alcanzoCupo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws EdicionNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     * @throws UsuarioYaRegistradoEnEdicionException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/altaRegistroRequest", output = "http://publicadores/PublicadorRegistro/altaRegistroResponse", fault = {
        @FaultAction(className = UsuarioYaRegistradoEnEdicionException_Exception.class, value = "http://publicadores/PublicadorRegistro/altaRegistro/Fault/UsuarioYaRegistradoEnEdicionException"),
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/altaRegistro/Fault/UsuarioNoExisteException")
    })
    public String altaRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DTFecha arg3,
        @WebParam(name = "arg4", partName = "arg4")
        double arg4)
        throws UsuarioNoExisteException_Exception, UsuarioYaRegistradoEnEdicionException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     * @throws EdicionNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/listarTipoRegistroRequest", output = "http://publicadores/PublicadorRegistro/listarTipoRegistroResponse", fault = {
        @FaultAction(className = EdicionNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/listarTipoRegistro/Fault/EdicionNoExisteException")
    })
    public StringArray listarTipoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws EdicionNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.DtRegistroArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/listarRegistrosPorAsistenteRequest", output = "http://publicadores/PublicadorRegistro/listarRegistrosPorAsistenteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/listarRegistrosPorAsistente/Fault/UsuarioNoExisteException")
    })
    public DtRegistroArray listarRegistrosPorAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns soap.DtTipoDeRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/consultaTipoDeRegistroRequest", output = "http://publicadores/PublicadorRegistro/consultaTipoDeRegistroResponse")
    public DtTipoDeRegistro consultaTipoDeRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorRegistro/registrarAsistenciaRequest", output = "http://publicadores/PublicadorRegistro/registrarAsistenciaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/registrarAsistencia/Fault/UsuarioNoExisteException")
    })
    public void registrarAsistencia(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/obtenerNomsTipoRegistroRequest", output = "http://publicadores/PublicadorRegistro/obtenerNomsTipoRegistroResponse")
    public StringArray obtenerNomsTipoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     * @throws UsuarioNoPerteneceException_Exception
     * @throws UsuarioYaRegistradoEnEdicionException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorRegistro/altaRegistroConPatrocinioRequest", output = "http://publicadores/PublicadorRegistro/altaRegistroConPatrocinioResponse", fault = {
        @FaultAction(className = UsuarioYaRegistradoEnEdicionException_Exception.class, value = "http://publicadores/PublicadorRegistro/altaRegistroConPatrocinio/Fault/UsuarioYaRegistradoEnEdicionException"),
        @FaultAction(className = UsuarioNoPerteneceException_Exception.class, value = "http://publicadores/PublicadorRegistro/altaRegistroConPatrocinio/Fault/UsuarioNoPerteneceException"),
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorRegistro/altaRegistroConPatrocinio/Fault/UsuarioNoExisteException")
    })
    public String altaRegistroConPatrocinio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DTFecha arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws UsuarioNoExisteException_Exception, UsuarioNoPerteneceException_Exception, UsuarioYaRegistradoEnEdicionException_Exception
    ;

}
