
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/** 
 * Esto no se toca, se genera automaticamente con wsimport
 * 
*/

/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:9128/publicador?wsdl")
public class PublicadorControladorService
    extends Service
{

    private static final URL PUBLICADORCONTROLADORSERVICE_WSDL_LOCATION;
    private static final WebServiceException PUBLICADORCONTROLADORSERVICE_EXCEPTION;
    private static final QName PUBLICADORCONTROLADORSERVICE_QNAME = new QName("http://publicadores/", "PublicadorControladorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/publicador?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORSERVICE_QNAME);
    }

    public PublicadorControladorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORSERVICE_QNAME, features);
    }

    public PublicadorControladorService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORSERVICE_QNAME);
    }

    public PublicadorControladorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORSERVICE_QNAME, features);
    }

    public PublicadorControladorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControlador
     */
    @WebEndpoint(name = "PublicadorControladorPort")
    public PublicadorControlador getPublicadorControladorPort() {
        return super.getPort(new QName("http://publicadores/", "PublicadorControladorPort"), PublicadorControlador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControlador
     */
    @WebEndpoint(name = "PublicadorControladorPort")
    public PublicadorControlador getPublicadorControladorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PublicadorControladorPort"), PublicadorControlador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORSERVICE_WSDL_LOCATION;
    }

}
