
package soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorUsuario", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorUsuario {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/cargarDatosPruebaRequest", output = "http://publicadores/PublicadorUsuario/cargarDatosPruebaResponse")
    public String cargarDatosPrueba();

    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarOrganizadoresRequest", output = "http://publicadores/PublicadorUsuario/listarOrganizadoresResponse")
    public StringArray listarOrganizadores();

    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarInstitucionesRequest", output = "http://publicadores/PublicadorUsuario/listarInstitucionesResponse")
    public StringArray listarInstituciones();

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarEdicionesOrganizadorRequest", output = "http://publicadores/PublicadorUsuario/listarEdicionesOrganizadorResponse")
    public StringArray listarEdicionesOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/validarCredencialesRequest", output = "http://publicadores/PublicadorUsuario/validarCredencialesResponse")
    public boolean validarCredenciales(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerRegistrosDetalladosRequest", output = "http://publicadores/PublicadorUsuario/obtenerRegistrosDetalladosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerRegistrosDetallados/Fault/UsuarioNoExisteException")
    })
    public StringArray obtenerRegistrosDetallados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarAsistentesRequest", output = "http://publicadores/PublicadorUsuario/listarAsistentesResponse")
    public StringArray listarAsistentes();

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/getDTUsuarioRequest", output = "http://publicadores/PublicadorUsuario/getDTUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/getDTUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuario getDTUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns soap.DtUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarUsuariosDTRequest", output = "http://publicadores/PublicadorUsuario/listarUsuariosDTResponse")
    public DtUsuarioArray listarUsuariosDT();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerTipoUsuarioRequest", output = "http://publicadores/PublicadorUsuario/obtenerTipoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerTipoUsuario/Fault/UsuarioNoExisteException")
    })
    public String obtenerTipoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerEmailRequest", output = "http://publicadores/PublicadorUsuario/obtenerEmailResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerEmail/Fault/UsuarioNoExisteException")
    })
    public String obtenerEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerNombreRequest", output = "http://publicadores/PublicadorUsuario/obtenerNombreResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerNombre/Fault/UsuarioNoExisteException")
    })
    public String obtenerNombre(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarUsuariosRequest", output = "http://publicadores/PublicadorUsuario/listarUsuariosResponse")
    public StringArray listarUsuarios();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns boolean
     * @throws CorreoInvalidoException_Exception
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/altaAsistenteRequest", output = "http://publicadores/PublicadorUsuario/altaAsistenteResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaAsistente/Fault/UsuarioRepetidoException"),
        @FaultAction(className = CorreoInvalidoException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaAsistente/Fault/CorreoInvalidoException"),
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaAsistente/Fault/FechaInvalidaException")
    })
    public boolean altaAsistente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        int arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9)
        throws CorreoInvalidoException_Exception, FechaInvalidaException_Exception, UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerAvatarRequest", output = "http://publicadores/PublicadorUsuario/obtenerAvatarResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerAvatar/Fault/UsuarioNoExisteException")
    })
    public String obtenerAvatar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.DtInstitucion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/getInstitucionRequest", output = "http://publicadores/PublicadorUsuario/getInstitucionResponse")
    public DtInstitucion getInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/modificarUsuarioRequest", output = "http://publicadores/PublicadorUsuario/modificarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/modificarUsuario/Fault/UsuarioNoExisteException"),
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://publicadores/PublicadorUsuario/modificarUsuario/Fault/FechaInvalidaException")
    })
    public boolean modificarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtUsuario arg1)
        throws FechaInvalidaException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns boolean
     * @throws CorreoInvalidoException_Exception
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/altaOrganizadorRequest", output = "http://publicadores/PublicadorUsuario/altaOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaOrganizador/Fault/UsuarioRepetidoException"),
        @FaultAction(className = CorreoInvalidoException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaOrganizador/Fault/CorreoInvalidoException")
    })
    public boolean altaOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws CorreoInvalidoException_Exception, UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerRegistrosRequest", output = "http://publicadores/PublicadorUsuario/obtenerRegistrosResponse")
    public StringArray obtenerRegistros(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns boolean
     * @throws ExisteInstitucionException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/altaInstitucionRequest", output = "http://publicadores/PublicadorUsuario/altaInstitucionResponse", fault = {
        @FaultAction(className = ExisteInstitucionException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaInstitucion/Fault/ExisteInstitucionException")
    })
    public boolean altaInstitucion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws ExisteInstitucionException_Exception
    ;

}
