
package soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorControlador", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorControlador {


    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/listarCategoriasRequest", output = "http://publicadores/PublicadorControlador/listarCategoriasResponse")
    public StringArray listarCategorias();

    /**
     * 
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/listarEventosRequest", output = "http://publicadores/PublicadorControlador/listarEventosResponse")
    public StringArray listarEventos();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/obtenerEventosRequest", output = "http://publicadores/PublicadorControlador/obtenerEventosResponse")
    public String obtenerEventos();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/altaCategoriaRequest", output = "http://publicadores/PublicadorControlador/altaCategoriaResponse")
    public boolean altaCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/darAltaEventoRequest", output = "http://publicadores/PublicadorControlador/darAltaEventoResponse")
    public String darAltaEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DTFecha arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        StringArray arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/cargarDatosPruebaRequest", output = "http://publicadores/PublicadorControlador/cargarDatosPruebaResponse")
    public String cargarDatosPrueba();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/holaRequest", output = "http://publicadores/PublicadorControlador/holaResponse")
    public String hola();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/altaEdicionDeEventoRequest", output = "http://publicadores/PublicadorControlador/altaEdicionDeEventoResponse")
    public boolean altaEdicionDeEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        DTFecha arg6,
        @WebParam(name = "arg7", partName = "arg7")
        DTFecha arg7,
        @WebParam(name = "arg8", partName = "arg8")
        DTFecha arg8);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/obtenerDetalleEventoRequest", output = "http://publicadores/PublicadorControlador/obtenerDetalleEventoResponse")
    public StringArray obtenerDetalleEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorControlador/listarEdicionesDeEventoRequest", output = "http://publicadores/PublicadorControlador/listarEdicionesDeEventoResponse")
    public StringArray listarEdicionesDeEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
