
package soap;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioYaRegistradoEnEdicionFault", targetNamespace = "http://publicadores/")
public class UsuarioYaRegistradoEnEdicionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioYaRegistradoEnEdicionException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioYaRegistradoEnEdicionException_Exception(String message, UsuarioYaRegistradoEnEdicionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioYaRegistradoEnEdicionException_Exception(String message, UsuarioYaRegistradoEnEdicionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap.UsuarioYaRegistradoEnEdicionException
     */
    public UsuarioYaRegistradoEnEdicionException getFaultInfo() {
        return faultInfo;
    }

}
